server:
  port: 8081

paypal:
  client-id: AdDXP-YLzKjAUvavqYGjVZEOb-ffj9cfvYOpnnFuOf8l5yjtxEXCJvqEMJ5uxJQfjwS6yYD-hyk4xEJr
  client-secret: ENb0tJ92K9IrKk4QrVldiaLR8nCMLtvfU7IC07T_NE-sYgp5lHO0SYDEVgSj-Ht3r2ltpQ0RteEoKQxu
  mode: sandbox

spring:
  application:
    name: hotelmore
  datasource:
    name: appointment
    url: jdbc:mysql://localhost:3306/hotelmore
    username: root
    password: More@786
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
  redis:
    host: localhost
    port: 6379

